apiVersion: v1
kind: Pod
metadata:
  name: sst-sync
  labels:
    tier: api
spec:
  containers:
  - name: sst-sync
    imagePullPolicy: Always
    image: argovis/noaa-sst:dev
    #command: ['sleep', '1000000']
    resources:
      requests:
        memory: "0Gi"
        cpu: "0m"
      limits:
        memory: 2000Mi
        cpu: 1000m
  restartPolicy: Never
