apiVersion: v1
kind: Pod
metadata:
  name: sst-proofread
  labels:
    tier: api
spec:
  containers:
  - name: sst-proofread
    imagePullPolicy: Always
    image: argovis/noaa-sst:proofread
    #command: ['sleep', '1000000']
    resources:
      requests:
        memory: "0Gi"
        cpu: "0m"
      limits:
        memory: 1000Mi
        cpu: 200m
  restartPolicy: Never
